### ISSUE TITLE
Testing checklist

### ISSUE THREAD

**Issue by leahriffell** [leahriffell/monster_shop_final#17]
- [ ] Item discounts display on order show page 
- [ ] Item discounts display on cart show page 
- [ ] Subtotal w/ discount displays on order show page 
- [ ] Subtotal w/ discount displays on cart show page 
- [ ] Multiple merchants w/ discounts in one order
- [ ] Multiple merchant items w/ discounts in one order
